site_name: FormBlocks
docs_dir: core/components/formblocks/docs
site_dir: _build/site
repo_url: https://github.com/Qaraqter/formblocks.git
pages:
- [index.md, Home]
- [config/overview.md, Configuration, Installation overview]
- [config/cb-import.md, Configuration, Import CB elements]
- [config/cb-settings.md, Configuration, Configure CB elements]
- [config/system-settings.md, Configuration, System settings]
- [config/email-rows.md, Configuration, Email row chunks]
- [fields/form.md, ContentBlocks Fields, Form field]
- [fields/input.md, ContentBlocks Fields, Input fields]
- [fields/select.md, ContentBlocks Fields, Selectable options]
- [fields/accept-terms.md, ContentBlocks Fields, Accept Terms checkbox]
- [notes/notes.md, Notes, Additional information]
theme: readthedocs
